name: check

on: pull_request

jobs:
  check:
    # if: "!contains(github.event.head_commit.message, 'chore(deps)')"
    # if: startsWith(github.head_ref, 'dependabot/') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install packages
        run: yarn install
      - name: Linter
        run: yarn lint
